name: Scheduled Twitter Bot

on:
  schedule:
    - cron: '0 6 * * *'   # Runs at 6:00 UTC daily
    - cron: '0 12 * * *'  # Runs at 12:00 UTC
    - cron: '0 18 * * *'  # Runs at 18:00 UTC
    - cron: '0 23 * * *'  # Runs at 23:00 UTC
  workflow_dispatch:      # Allows manual run from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Twitter Bot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: TWITTER_BOT.py
